#
# To connect from adminer: specify service name (mysql) rather than the container's IP address (localhost)
# To connect from mysql client: mysql -u root -h 127.0.0.1 -p
#
version: '3.8'
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: s3c4Et
      MYSQL_USER: test
      MYSQL_PASSWORD: changeMe
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/fleet.sql:/docker-entrypoint-initdb.d/fleet.sql"
    healthcheck:
      test: [ "CMD", "echo 'SELECT version();'| mysql" ]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - "8081:8080"
    depends_on:
      - mysql